server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5444/user
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: "userRegisterEvent:com.omerkoc.auth_service.dto.UserRegisterEvent,userLoginEvent:com.omerkoc.auth_service.dto.UserLoginEvent"

application:
  security:
    jwt:
      secret-key: "LupHyt72hUvCWSoxznpeN5D96l2npsa0tzVU1rXcUwd"
      expiration: 86400000 # default 24 hours

springdoc:
  api-docs:
    path: /auth/v3/api-docs
