spring:
  data:
    mongodb:
      username: glaymet
      password: glaymet
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

server:
  port: 8090

springdoc:
  api-docs:
    path: /customers/v3/api-docs

