server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**

            - id: customer-service
              uri: lb://customer-service
              predicates:
                - Path=/customers/**
              filters:
                - AuthenticationFilter

            - id: wallet-service
              uri: lb://wallet-service
              predicates:
                - Path=/wallets/**
              filters:
                - AuthenticationFilter
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: auth-service
        url: /auth/v3/api-docs
      - name: customer-service
        url: /customers/v3/api-docs
      - name: wallet-service
        url: /wallets/v3/api-docs