server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Route for Authentication Service (Public / Unsecured)
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**

            # Route for Customer Service (Secured with JWT filter)
            - id: customer-service
              uri: lb://customer-service # lb sayesinde eurekadan çeker
              predicates:
                - Path=/customers/**
              filters:
                - AuthenticationFilter
management:
  endpoint:
    gateway:
      enabled: true # gateway endpointlerini aktif eder
  endpoints:
    web:
      exposure:
        include: "*" #  endpoinlerin  hepsini dışarı açar

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: auth-service
        url: /auth/v3/api-docs
      - name: customer-service
        url: /customers/v3/api-docs
