server:
  port: 8085

spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS}
    consumer:
      group-id: notification-group-v2
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "*"
      spring.json.type.mapping: "userRegisterEvent:com.omerkoc.notification.dto.UserRegisterEvent,userLoginEvent:com.omerkoc.notification.dto.UserLoginEvent"
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true