name: Spring Boot CI-CD Pipeline

# Bu pipeline ne zaman çalışsın?
on:
  push:
    branches: ["main", "master"] # Sadece main veya master branch'ine push attığında tetiklenir

jobs:
  build-and-test:
    runs-on: ubuntu-latest # GitHub bizim için arkada tertemiz bir Ubuntu makine açıyor

    steps:
      # 1. Adım: GitHub'daki kodlarımızı bu Ubuntu makinesine çekiyoruz
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Adım: Java 17 (veya senin sürümün neyse) ortamını kuruyoruz
      - name: Set up JDK 21
        uses: actions/environments/java@v4 # Not: Standart setup-java aksiyonudur
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven # Maven bağımlılıklarını önbelleğe alır ki sonraki build'ler jet gibi hızlı olsun

      # 3. Adım: Kodumuzu derliyoruz ve testleri koşuyoruz (Jar dosyasını basıyoruz)
      - name: Build with Maven
        run: mvn clean package -DskipTests=false # İlk etapta testlerin varsa koşsun, patlarsa pipeline dursun diye false bıraktım

      # 4. Adım: Docker Compose dosyasının sözdizimi (syntax) doğru mu diye kontrol ediyoruz
      - name: Check Docker Compose Config
        run: docker compose config
