name: Spring Boot CI-CD Pipeline

on:
  push:
    branches: ["main", "master"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          [
            "auth-service",
            "config-server",
            "customer",
            "discovery",
            "gateway",
            "notification",
            "wallet",
          ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Build ${{ matrix.service }}
        working-directory: ./services/${{ matrix.service }}
        run: mvn clean package -DskipTests=true

  check-docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Docker Compose Config
        working-directory: ./services
        run: docker compose config
