name: Spring Boot CI-CD Pipeline

on:
  push:
    branches: ["main", "master"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Java 21 Ayarı
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      # auth-service klasörüne gidip orayı derliyoruz
      - name: Build Auth Service
        working-directory: ./services/auth-service
        run: mvn clean package -DskipTests=true

      # docker-compose.yml dosyasının olduğu klasöre gidip kontrol ediyoruz
      - name: Check Docker Compose Config
        working-directory: ./services
        run: docker compose config
