spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:http://localhost:8888"
  security:
    jwt:
      secret-key: LupHyt72hUvCWSoxznpeN5D96l2npsa0tzVU1rXcUwd
      expiration: 86400000 # default 24 hours
